#!/bin/zsh

# get submodules and update
git submodule init
git submodule update
rcup

# copy systemd templates, unfortunately symbolic links can not be used.
for file in $HOME/.config/systemd-templates/**/*.template; do
  filename=${file##*/}

  if [ ! -f $HOME/.config/systemd/user/${filename%.template} ]; then
    cp $file $HOME/.config/systemd/user/${filename%.template}
  fi
done

# get/set gitconfig details
if [[ $(echo `git config user.name`) == "" ]]; then
  echo "\nPlease enter your full name (this will show on git commits): "
  read git_user_name
  git config --file ~/.gitconfig.local --replace-all user.name "$git_user_name"
fi

if [[ $(echo `git config user.email`) == "" ]]; then
  echo "\nPlease enter your email address (this should be the same email attached to your github account): "
  read git_user_email
  git config --file ~/.gitconfig.local --replace-all user.email "$git_user_email"
fi

if [[ $(echo `git config github.username`) == "" ]]; then
  echo "\nPlease enter your github username: "
  read git_github_username
  git config --file ~/.gitconfig.local --replace-all github.user "$git_github_username"
fi

# reload new zshrc
source ~/.zshrc
