#!/bin/zsh

# remove exisiting zsh-syntax-highlighting directory and clone again
rm -rf zsh-syntax-highlighting
git clone git://github.com/zsh-users/zsh-syntax-highlighting.git
rcup

# remove exisiting wee-slack directory and clone again
rm -rf scripts/wee-slack
git clone git://github.com/rawdigits/wee-slack.git scripts/wee-slack
rm ~/.weechat/python/autoload/wee_slack.py
rcup
ln -s ~/.scripts/wee-slack/wee_slack.py ~/.weechat/python/autoload/wee_slack.py

# get/set gitconfig details
if [[ $(echo `git config user.name`) == "" ]]; then
  echo "\nPlease enter your full name (this will show on git commits): "
  read git_user_name
  git config --file ~/.gitconfig.local --replace-all user.name "$git_user_name"
fi

if [[ $(echo `git config user.email`) == "" ]]; then
  echo "\nPlease enter your email address (this should be the same email attached to your github account): "
  read git_user_email
  git config --file ~/.gitconfig.local --replace-all user.email "$git_user_email"
fi

if [[ $(echo `git config github.username`) == "" ]]; then
  echo "\nPlease enter your github username: "
  read git_github_username
  git config --file ~/.gitconfig.local --replace-all github.user "$git_github_username"
fi

# reload new zshrc
source ~/.zshrc
