# load Xresources
xrdb -load ~/.Xresources &
xrdb -merge ~/.Xresources

#load xmodmap
xmodmap ~/.Xmodmap

#create i3 config
~/.i3/create_config

# Host specific env vars
[[ -f ~/.env.local ]] && source ~/.env.local

#start i3
exec i3
