#!/bin/sh

start_mopidy() {
  local spotify_password="$(~/.local/bin/getnetrc kenyonj@spotify.com)"
  local spotify_client_id="$(~/.local/bin/getnetrc kenyonj@spotifyid.com)"
  local spotify_client_secret="$(~/.local/bin/getnetrc kenyonj@spotifysecret.com)"
  local gmusic_password="$(~/.local/bin/getnetrc kenyonj@gmail.com)"
  local soundcloud_auth_token="$(~/.local/bin/getnetrc justin@soundcloud.com)"
  /usr/bin/mopidy \
    -o "spotify/password=$spotify_password" \
    -o "spotify/client_id=$spotify_client_id" \
    -o "spotify/client_secret=$spotify_client_secret" \
    -o "gmusic/password=$gmusic_password" \
    -o "soundcloud/auth_token=$soundcloud_auth_token"
}

start_mopidy
