#!/bin/sh

## Initialize which monitors are connected
xrandr | grep DP2 | grep " connected "
if [$? -eq 0]; then
    # External monitor is connected
    xrandr --output VIRTUAL1 --off --output eDP1 --mode 1920x1200 --pos 2624x328 --rotate normal --output DP1 --off --output HDMI3 --off --output HDMI2 --off --output HDMI1 --off --output VGA1 --off --output DP2 --mode 2560x1600 --pos 0x0 --rotate normal
else
    # External monitor is not connected
    xrandr --output VIRTUAL1 --off --output eDP1 --mode 1920x1200 --pos 2624x328 --rotate normal --output DP1 --off --output HDMI3 --off --output HDMI2 --off --output HDMI1 --off --output VGA1 --off --output DP2 --off
fi

i3-msg "mode default"
