#!/bin/sh

## Start slack windows
i3-msg "workspace 10: slacks; append_layout ~/.i3/workspace_10.json"
i3-msg "workspace 10: slacks; exec --no-startup-id google-chrome-stable --app='https://thoughtbot.slack.com'"
i3-msg "workspace 10: slacks; exec --no-startup-id google-chrome-stable --app='https://kenyon.slack.com'"
i3-msg "workspace 10: slacks; exec --no-startup-id google-chrome-stable --app='https://twentyeightmusic.slack.com'"
i3-msg "mode default"
