#!/bin/bash

i3-msg "workspace 1:; append_layout ~/.workspaces/music.json"

i3-msg "workspace 1:; exec termite -t "ncmpcpp" -e ncmpcpp"
i3-msg "workspace 1:; exec termite -t "visualizer" -e vis"
i3-msg "workspace 1:; exec ~/.scripts/display_cover.sh"
