#!/bin/sh

start_mopidy() {
  local spotify_password="$(~/.local/bin/getnetrc kenyonj@spotify.com)"
  local gmusic_password="$(~/.local/bin/getnetrc kenyonj@gmusic.password)"
  local gmusic_device_id="$(~/.local/bin/getnetrc kenyonj@gmusic.device-id)"
  /usr/bin/mopidy -o "spotify/password=$spotify_password" -o "gmusic/password=$gmusic_password" -o "gmusic/deviceid=$gmusic_device_id"
}

start_mopidy
